# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elf_name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('sposored', models.ManyToManyField(related_name='sponsorer', to='login.User')),
            ],
        ),
    ]
